### ISSUE TITLE
web demo : restrict shape size min/max in options

### ISSUE THREAD

**Issue by mastef** [Tw1ddle/geometrize-haxe#10]
Would be nice to restrict shape size min/max per step in the options. This way I would start with huge shapes in the beginning, and progressively in later stages reduce the size when more details should be added.

( Would work great with the focus areas from #3 )

**Comment by Tw1ddle** [comment]
I've implemented this capability in my C++ desktop app via an embedded scripting language, you can implement this limit via your own scripts. I'll release a new build of very soon with this in (https://github.com/Tw1ddle/geometrize).

As with other stuff, I'm not planning to implement the feature again in Haxe, so I'm closing this.
