### ISSUE TITLE
image quality is bad at Geode

### ISSUE THREAD

**Issue by example-account96** [Tw1ddle/geometrize-haxe#23]
when i download the .json, it is perfectly fine
but when i export it to GD via Geode, this happens:
![geometrized_svg](https://github.com/user-attachments/assets/15f85fa1-b88e-4a4a-9a7c-9a50c61fa850)
expected image (the svg showing every square, rectangle, triangle, circle and lines which i chose)
![Screenshot_20240811-205101_Geode](https://github.com/user-attachments/assets/156ada0c-e448-4d58-9317-2a3ae0ccdaf7)
what came (only the circles)

is this a bug?

**Comment by Tw1ddle** [comment]
As you say it seems like the GD importer you're using is only loading in or rendering the circles. Likely not a bug and it probably only supports circles, just supposing.

In any case it's not something I would fix here, I didn't write Geode nor play much Geometry Dash.

**Comment by example-account96** [comment]
thanks, i successfully got the image at Geode using only circles.

Em ter., 13 de ago. de 2024 01:12, Sam Twidale ***@***.***>
escreveu:
