### ISSUE TITLE
web demo : strategy based on steps

### ISSUE THREAD

**Issue by mastef** [Tw1ddle/geometrize-haxe#4]
more of a convenience feature : being able to decide on strategies based on steps. e.g. first 300 steps triangles, then 300-1000 switch to ellipses, then finally 1000+ enable ellipses, lines and rectangles

**Comment by Tw1ddle** [comment]
I've implemented this capability in my C++ desktop app via an embedded scripting language, you can implement all sorts of strategies. I'll release a new build of very soon with this in (https://github.com/Tw1ddle/geometrize). 

With a bunch of work something similar could be done with hscript or similar, but I'm not planning to implement the feature again in Haxe, so I'm closing this.
